fixtures:
  repositories:
    firewall:
      repo: "https://github.com/puppetlabs/puppetlabs-firewall.git"
      ref:  "master"
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
  symlinks:
    base_firewall: "#{source_dir}"
